/**
 * Full Singapore used-car make/model catalogue for filters & search.
 * Models are the common SGCM-style names buyers search for.
 */
export const SG_MODELS_BY_MAKE: Record<string, string[]> = {
  Toyota: [
    "Corolla Altis",
    "Camry",
    "Vios",
    "Yaris",
    "CHR",
    "RAV4",
    "Harrier",
    "Fortuner",
    "Wish",
    "Sienta",
    "Alphard",
    "Vellfire",
    "Prius",
    "Aqua",
    "Estima",
    "Innova",
    "Hiace",
  ],
  Honda: [
    "Civic",
    "Accord",
    "City",
    "Jazz",
    "Fit",
    "Vezel",
    "HR-V",
    "CR-V",
    "Stream",
    "Odyssey",
    "Freed",
    "Shuttle",
  ],
  "Mercedes-Benz": [
    "A-Class",
    "B-Class",
    "C-Class",
    "E-Class",
    "S-Class",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "V-Class",
  ],
  BMW: [
    "1 Series",
    "2 Series",
    "3 Series",
    "5 Series",
    "7 Series",
    "X1",
    "X3",
    "X5",
    "X7",
    "Z4",
    "iX",
    "i4",
  ],
  Audi: ["A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "e-tron"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "CX-8", "CX-9", "MX-5"],
  Nissan: ["Almera", "Sylphy", "Teana", "Qashqai", "X-Trail", "Serena", "Elgrand", "Leaf", "Note"],
  Hyundai: ["Accent", "Elantra", "Avante", "Sonata", "Tucson", "Santa Fe", "Ioniq", "Kona", "Staria"],
  Kia: ["Cerato", "K5", "Sportage", "Sorento", "Carnival", "EV6", "Seltos", "Niro"],
  Volkswagen: ["Golf", "Polo", "Passat", "Jetta", "Tiguan", "Touran", "Arteon", "ID.4"],
  Lexus: ["CT", "IS", "ES", "GS", "LS", "NX", "RX", "UX", "LM"],
  Subaru: ["Impreza", "Legacy", "Forester", "XV", "Outback", "WRX", "BRZ"],
  Mitsubishi: ["Lancer", "Attrage", "ASX", "Outlander", "Pajero", "Eclipse Cross", "Delica"],
  Volvo: ["S60", "S90", "V60", "XC40", "XC60", "XC90", "C40"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "Cayman"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X"],
  MINI: ["Cooper", "Cooper S", "Clubman", "Countryman", "Convertible"],
  Suzuki: ["Swift", "Vitara", "SX4", "Jimny", "Ertiga", "Baleno"],
  Ford: ["Focus", "Fiesta", "Mondeo", "Kuga", "Escape", "Ranger", "Mustang"],
  Peugeot: ["208", "308", "508", "2008", "3008", "5008"],
  Renault: ["Clio", "Megane", "Captur", "Kadjar", "Koleos", "Scenic"],
  Skoda: ["Fabia", "Octavia", "Superb", "Kodiaq", "Karoq", "Scala"],
  Citroen: ["C3", "C4", "C5", "Berlingo", "C5 Aircross"],
  "Land Rover": ["Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Defender"],
  Jaguar: ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace", "F-Type"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Giulietta", "Tonale"],
  Ferrari: ["488", "F8", "Roma", "Portofino", "SF90", "296"],
  Lamborghini: ["Huracan", "Urus", "Aventador", "Revuelto"],
  Maserati: ["Ghibli", "Quattroporte", "Levante", "Grecale", "MC20"],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga"],
  "Rolls-Royce": ["Ghost", "Phantom", "Cullinan", "Wraith", "Dawn"],
  BYD: ["Atto 3", "Seal", "Dolphin", "Sealion 7", "Tang"],
  MG: ["ZS", "HS", "5", "4", "Cyberster"],
  Chery: ["Tiggo 7", "Tiggo 8", "Omoda 5", "Arrizo"],
  GWM: ["Haval Jolion", "Haval H6", "Ora Good Cat", "Tank 300"],
  Opel: ["Astra", "Corsa", "Crossland", "Grandland", "Mokka"],
  Seat: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"],
  Perodua: ["Myvi", "Axia", "Bezza", "Aruz", "Ativa"],
  Proton: ["Saga", "Persona", "Iriz", "X50", "X70", "X90"],
  Daihatsu: ["Terios", "Sirion", "Move", "Rocky"],
  Isuzu: ["D-Max", "MU-X", "NPR"],
  Jeep: ["Wrangler", "Cherokee", "Grand Cherokee", "Compass", "Renegade"],
  Chevrolet: ["Cruze", "Malibu", "Captiva", "Trax", "Orlando"],
  Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80"],
  Genesis: ["G70", "G80", "GV70", "GV80"],
  Polestar: ["2", "3", "4"],
  Smart: ["Fortwo", "Forfour", "#1", "#3"],
  Fiat: ["500", "Panda", "Tipo", "500X"],
  Chrysler: ["300C", "Pacifica", "Voyager"],
  Dodge: ["Challenger", "Charger", "Journey", "Durango"],
  Hummer: ["H2", "H3", "EV"],
  Ssangyong: ["Tivoli", "Korando", "Rexton", "Musso"],
  "Aston Martin": ["DB11", "DB12", "Vantage", "DBX", "DBS"],
  McLaren: ["570S", "720S", "Artura", "GT", "765LT"],
  Lotus: ["Emira", "Evora", "Elise", "Eletre"],
};

export const SG_MAKES = Object.keys(SG_MODELS_BY_MAKE).sort((a, b) =>
  a.localeCompare(b),
);

/** Popular brands for homepage chips when inventory is thin. */
export const SG_POPULAR_MAKES = [
  "Toyota",
  "Honda",
  "Mercedes-Benz",
  "BMW",
  "Mazda",
  "Nissan",
  "Hyundai",
  "Kia",
  "Audi",
  "Volkswagen",
  "Lexus",
  "Tesla",
  "BYD",
  "Porsche",
];
